<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Authentification</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>ec2f6c7c-3bc6-4bf2-a42a-505c4d2e8389</testSuiteGuid>
   <testCaseLink>
      <guid>7c003ddc-0a4d-457d-863c-dcc7cd3a4667</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TestDataDrivenLogin</testCaseId>
      <testDataLink>
         <combinationType>MANY</combinationType>
         <id>463ba60b-6338-41a9-b56c-268e8d6e37fc</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/data1</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>463ba60b-6338-41a9-b56c-268e8d6e37fc</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>${username}</value>
         <variableId>38c0981b-a4ce-4e06-8282-ae6b48b0fac5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>463ba60b-6338-41a9-b56c-268e8d6e37fc</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>${password}</value>
         <variableId>2857c94f-554f-47b7-bb9c-d1d2120c8517</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>463ba60b-6338-41a9-b56c-268e8d6e37fc</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>${ExpectedResult}</value>
         <variableId>c6d34fdf-bd80-45ce-992b-e73b0130ef3e</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
